
trigger:
  branches:
    include:
    - develop    
    - main
variables:
- group: azure
- name: azureSubscription
  value: 'azureSubscription'
  
pool:
  vmImage: 'ubuntu-18.04'  
stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.0.x'
          displayName: 'Set SDK to 6.0.x'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '$(Build.SourcesDirectory)/src/AOM.FIFA.ManagerPlayer.Api/AOM.FIFA.ManagerPlayer.Api.csproj'
          displayName: 'Build backend service'

        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '$(Build.SourcesDirectory)/src/AOM.FIFA.ManagerPlayer.Api/AOM.FIFA.ManagerPlayer.Api.csproj'
            arguments: '-o $(Build.ArtifactStagingDirectory)'
          displayName: 'dotnet publish'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

        - task: PublishBuildArtifacts@1
          inputs:
            PathToPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '$[azure.azureSubscription]'
            appType: 'webAppLinux'
            WebAppName: 'AOMFIFAManagerPlayerApi'
            packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
            RuntimeStack: 'DOTNETCORE|6.0'




